name: Build Main

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.gitignore'
      - '**/*.gitattributes'
    workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [Windows-latest, ubuntu-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4
    - name: Setup Runtimes, Caching
      uses: ./.github/actions/setup-runtimes-caching
      with:
        name: "Full"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }}

  tests:
    uses: ./.github/workflows/test.yml