name: .NET main

on:
  push:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [Windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }}
    - name: Test
      run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --verbosity normal