name: Publish NuGet Packages

on:
  workflow_call:

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages

    - name: Publish to NuGet
      run: |
        ls -al ./
        dotnet nuget push ./*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate